server:
  port: 9002
spring:
  application:
    name: cloud-auth
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:8080/eureka/

# 配置Hystrix熔断机制
feign:
  hystrix:
    # 开启feign的Hystrix熔断器支持
    enabled: true




