spring:
  profiles:
    active: native
  cloud:
    config:
      uri: http://localhost:8888
      name: application
      profile: dev

#server:
#  port: 9003
#
#spring:
#  application:
#    name: cloud-zuul
#
#eureka:
#  client:
#    service-url:
#      # Eureka注册中心连接地址
#      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
#      defaultZone: http://localhost:8080/eureka/
#
#zuul:
#  routes:
#    # 路由名称，随意
#    cloud-admin:
#      path: /api/admin/**
#      # 该路由地址对应的服务名称
#      serviceId: cloud-admin
#    cloud-auth:
#      path: /api/auth/**
#      serviceId: cloud-auth
